services:
  - type: web
    name: hopeconnect
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: super_secret_jwt_token_key_for_viva_project_2026
      - key: DB_TYPE
        value: sqlite
